language: python
os: linux
python:
- 3.8
- 3.7
- 3.6
- 3.5
install: pip install -U tox-travis
script: tox
jobs:
  include:
  - stage: deploy
    script: make docs && touch docs/build/html/.nojekyll
    before_script:
    - pipenv install --dev --skip-lock
    - make install
    python: 3.6
    deploy:
      provider: pages
      local_dir: docs/build/html
      skip_cleanup: true
      token: "$GH_TOKEN"
      keep_history: true
      on:
        branch: master
  - stage: deploy
    script: pip install -e .
    before_script:
    - make ui
    python: 3.6
    deploy:
      provider: pypi
      username: __token__
      password:
        secure: EANoOitN/LJnw/mGTEFdQ80rGvXzDus8ABMgakxvVqVpCIbCGbaRxR3gPvEVm9AnHK7fdYPEf/p6ku9rczhrd2vTeLEO45Sn2kWMsQZ0flYRP3IwRD9FwjNYxbm/6OEoapIUjf6IwlWSQ9t9BhMi/7jNKnqWYxrYRPdCs7Mh0fUA/5UaoDQCXHppi7pmCOKLFwBBU9URrmAWu+zV6jzYr2Vsvr/f94y7zTz4gULW5Pef8W+LI6WNEQx4FIZmE+KBnEEKm44jREIBk8JI1YpxcgTM+NAfN2YYERF9qsF9YZnyD/gDOwj/c6zpMIfiy8HD3kiAkPLVLvIDCBbv976dREDGadhWx/pamlGExFavezjXr0696h0plP+KQqp9tfqNIIrnhkEDpyX1uoHSXIfIbFl2bQOs2VT/hi7hpK03dY6GmofuJ3c2RrDZnLkp+zJUvkQHkQL1qKFu0s0fA+BJLtBZn7jRn0UnSiq8VwH7EcvcnJOf7Yshf/Y3i4U32iG1jtMTGI/5aCCiQAUV6c9xj95f73D2NkbSz21cFWzGkQCbJBTdOt8p0zO8sSijAeqC3OLEQoecTXxjz5uRKTdV23QFxPmDWk0Rx+7LgZi0/vd8ruqUVbdvGBseJjX/yWoVGH2q4LaqWIqehaJPoHSH9kZfOtCvPPwI05tPwmZJQS4=
      on:
        tags: true
