language: python
os: linux
python:
  - 3.8
  - 3.7
  - 3.6
  - 3.5

install: pip install -U tox-travis

script: tox

jobs:
  include:
    - stage: deploy
      script: make docs
      before_script:
        - pipenv install --dev
        - make install
      python: 3.6
      deploy:
        provider: pages
        local_dir: docs/build
        cleanup: false
        token: $GH_TOKEN
        keep_history: true
        on:
           branch: master